# Header

menu:
  主页: /
  随笔: /
  个人简历: /

# SubNav
subnav:
  github: "https://github.com/Belphegor95"
  # weibo: "#"5
  # rss: "#"
  # zhihu: "#"
  # qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:1040605621@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: false
google_analytics: false
# 直接放在文件夹下不行
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/litten.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: true

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
# gitment_owner: Belphegor95      #你的 GitHub ID
# gitment_repo: belphegor95-blogs          #存储评论的 repo
# gitment_oauth:
#   client_id: 2e28f861952d03f8e4c8             #client ID
#   client_secret: fa7fe403e1a90cdcaa345db260028b74a33248fb       #client secret

#6、Gitment
# giteement:
#   enable: true  # 是否启用码云评论系统
#   # 是否使用官方js(false可以提升访问速度)
#   remote: false
#   redirect_uri: http://www.belphegor95.cn/   # 应用回调地址(请和配置的第三方应用保持一致)
#   # 不能更改(网上开源项目https://github.com/Rob--W/cors-anywhere作者提供的专门用来跨域服务器的配置)
#   oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
#   giteeID: Belphegor95  # 你的码云账号英文名
#   # 存储评论的 repo
#   repo: belphegor95-blogs
#   gitment_oauth:
#     client_id: e6ff84e1607b8a1a0690d5d257569b0bf253537ee51506313c95c30726227f6b           #client ID
#     client_secret: 673dc274a1a690c977d9855d2cd5b745c4ce249231927e0c38e2316557925eea       #client secret

#7、Valine https://valine.js.org
valine: 
 appid: SyUgIn79HL8P5loDFjTX5LWX-gzGzoHsz  #Leancloud应用的appId
 appkey: xfzhCfIbhK7tg3GsRqpYA1tP  #Leancloud应用的appKey
 verify: false #验证码
 notify: false #评论回复提醒
 avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 #头像类型可见： https://valine.js.org/avatar.html
 placeholder: 写下你的评论! #评论框占位符
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#FFF'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  导师博客: https://www.psvmc.cn/

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: 121.199.55.220
  user: root
  root: /data/myblog/
  port: 22
  delete: true
  verbose: true
  ignore_errors: false

aboutme: Belphegor,<br>毕业于河南水利与环境<br>就职于郑州星火燎原软件<br><br><br>热爱计算机<br>现在只是一个小前端  